---
id: 2024-02-16
created_date: 16/02/2024
updated_date: 16/02/2024
type: note
---

#  2024-02-16

## üìù Notes

16/02/2024:02:23

```java

Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: 

HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)


    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

	at c3.platform.action.py.TurboPyInterpreter.callMethod(TurboPyInterpreter.java:172)
	at c3.platform.action.py.TurboPy.lambda$5(TurboPy.java:508)
	at c3.platform.typesys.type.TypeMeta_Methods.lambda$5(TypeMeta_Methods.java:288)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.callMethodType(Ctx.java:367)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:288)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:304)
	at c3.platform.typesys.type.TypeMeta_Impl.call(TypeMeta_Impl.java:4467)
	at c3.C3.dispatch(C3.java:448)
	at c3.platform.action.js.TurboJsMethod.callJava(TurboJsMethod.java:64)
	at c3.platform.action.js.TurboJsFunction.lambda$0(TurboJsFunction.java:34)
	at c3.platform.action.js.TurboJs.callWrapErr(TurboJs.java:839)
	at c3.platform.action.js.TurboJsFunction.call(TurboJsFunction.java:32)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.lambda_js_21._c_anonymous_1(lambda.js:11)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at c3.platform.action.js.TurboJs.lambda$15(TurboJs.java:432)
	at c3.platform.action.js.TurboJs.withRhinoContext(TurboJs.java:779)
	at c3.platform.action.js.TurboJs.lambda$11(TurboJs.java:413)
	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:358)
	... 82 more

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }

	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:373)
	at c3.platform.action.js.TurboJs.execLambda(TurboJs.java:412)
	at c3.platform.typesys.value.Lambda_Methods.applyJs(Lambda_Methods.java:95)
	at c3.platform.typesys.value.Lambda_Impl.applyJs(Lambda_Impl.java:345)
	at c3.platform.typesys.value.Lambda_Methods.apply(Lambda_Methods.java:69)
	at c3.platform.typesys.value.Lambda_Methods.call(Lambda_Methods.java:106)
	at c3.platform.typesys.value.Lambda_Impl.call(Lambda_Impl.java:303)
	at c3.platform.typesys.value.Lambda_Methods$1.call(Lambda_Methods.java:467)
	at c3.platform.typesys.util.function.AnyFunction$1.accept(AnyFunction.java:40)
	at c3.platform.cloud.apache.mapr.ObjBatchMapReduceJob_Methods.map(ObjBatchMapReduceJob_Methods.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	... 68 more

Called from Java action ObjBatchMapReduceJob#map

	at c3.platform.typesys.type.MethodType_Methods.handleException(MethodType_Methods.java:214)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:227)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$112(MapReduce_SubtypeImpl.java:1959)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:384)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.map(MapReduce_SubtypeImpl.java:1959)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMapForSubBatch(MapReduce_Methods.java:736)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMap(MapReduce_Methods.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	... 55 more

Called from Java action ObjBatchMapReduceJob#dispatchMap

	at c3.platform.typesys.type.MethodType_Methods.handleException(MethodType_Methods.java:214)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:227)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$129(MapReduce_SubtypeImpl.java:2050)
	at c3.Ctx.lambda$13(Ctx.java:416)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.run(Ctx.java:415)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.dispatchMap(MapReduce_SubtypeImpl.java:2050)
	at c3.platform.async.MapReduceQueue_Methods.lambda$0(MapReduceQueue_Methods.java:70)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.C3.lambda$26(C3.java:1173)
	at c3.C3.asUser(C3.java:1844)
	at c3.C3.asUser(C3.java:833)
	at c3.platform.async.MapReduceQueue_Methods.compute(MapReduceQueue_Methods.java:31)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	... 38 more

Called from Java action MapReduceQueue#compute

	at c3.platform.typesys.type.MethodType_Methods.handleException(MethodType_Methods.java:214)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:227)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.platform.async.InvalidationQueue_Methods.compute(InvalidationQueue_Methods.java:1085)
	at c3.platform.async.InvalidationQueue_Methods.doDispatchCompute(InvalidationQueue_Methods.java:301)
	at c3.platform.async.InvalidationQueue_Methods.dispatchCompute(InvalidationQueue_Methods.java:270)
	at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.C3.callWithSecondaryKey(C3.java:277)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$19(InvalidationQueue_Processor_Methods.java:418)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$16(InvalidationQueue_Processor_Methods.java:417)
	at c3.platform.async.Promise_Methods.lambda$1(Promise_Methods.java:32)
	at c3.platform.async.FulfillablePromise_Impl.lambda$12(FulfillablePromise_Impl.java:285)
	at c3.C3.callInLocalJvmApp(C3.java:178)
	at c3.platform.async.FulfillablePromise_Impl._run(FulfillablePromise_Impl.java:284)
	at c3.platform.async.Promise_Methods.lambda$0(Promise_Methods.java:32)
	at c3.C3.lambda$5(C3.java:141)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.C3.lambda$4(C3.java:141)
	at c3.Executor.lambda$4(Executor.java:156)
	at c3.C3.runWithAppId(C3.java:1029)
	at c3.C3.runInApp(C3.java:1020)
	at c3.C3.lambda$46(C3.java:1417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)


Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }

Called from Java action ObjBatchMapReduceJob#map

Called from Java action ObjBatchMapReduceJob#dispatchMap
Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

	at c3.platform.action.py.TurboPyInterpreter.callMethod(TurboPyInterpreter.java:172)
	at c3.platform.action.py.TurboPy.lambda$5(TurboPy.java:508)
	at c3.platform.typesys.type.TypeMeta_Methods.lambda$5(TypeMeta_Methods.java:288)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.callMethodType(Ctx.java:367)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:288)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:304)
	at c3.platform.typesys.type.TypeMeta_Impl.call(TypeMeta_Impl.java:4467)
	at c3.C3.dispatch(C3.java:448)
	at c3.platform.action.js.TurboJsMethod.callJava(TurboJsMethod.java:64)
	at c3.platform.action.js.TurboJsFunction.lambda$0(TurboJsFunction.java:34)
	at c3.platform.action.js.TurboJs.callWrapErr(TurboJs.java:839)
	at c3.platform.action.js.TurboJsFunction.call(TurboJsFunction.java:32)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.lambda_js_21._c_anonymous_1(lambda.js:11)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at c3.platform.action.js.TurboJs.lambda$15(TurboJs.java:432)
	at c3.platform.action.js.TurboJs.withRhinoContext(TurboJs.java:779)
	at c3.platform.action.js.TurboJs.lambda$11(TurboJs.java:413)
	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:358)
	... 82 more

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }

	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:373)
	at c3.platform.action.js.TurboJs.execLambda(TurboJs.java:412)
	at c3.platform.typesys.value.Lambda_Methods.applyJs(Lambda_Methods.java:95)
	at c3.platform.typesys.value.Lambda_Impl.applyJs(Lambda_Impl.java:345)
	at c3.platform.typesys.value.Lambda_Methods.apply(Lambda_Methods.java:69)
	at c3.platform.typesys.value.Lambda_Methods.call(Lambda_Methods.java:106)
	at c3.platform.typesys.value.Lambda_Impl.call(Lambda_Impl.java:303)
	at c3.platform.typesys.value.Lambda_Methods$1.call(Lambda_Methods.java:467)
	at c3.platform.typesys.util.function.AnyFunction$1.accept(AnyFunction.java:40)
	at c3.platform.cloud.apache.mapr.ObjBatchMapReduceJob_Methods.map(ObjBatchMapReduceJob_Methods.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	... 68 more

Called from Java action ObjBatchMapReduceJob#map

	at c3.platform.typesys.type.MethodType_Methods.handleException(MethodType_Methods.java:214)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:227)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$112(MapReduce_SubtypeImpl.java:1959)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:384)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.map(MapReduce_SubtypeImpl.java:1959)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMapForSubBatch(MapReduce_Methods.java:736)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMap(MapReduce_Methods.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	... 55 more

Called from Java action ObjBatchMapReduceJob#dispatchMap

	at c3.platform.typesys.type.MethodType_Methods.handleException(MethodType_Methods.java:214)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:227)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$129(MapReduce_SubtypeImpl.java:2050)
	at c3.Ctx.lambda$13(Ctx.java:416)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.run(Ctx.java:415)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.dispatchMap(MapReduce_SubtypeImpl.java:2050)
	at c3.platform.async.MapReduceQueue_Methods.lambda$0(MapReduceQueue_Methods.java:70)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.C3.lambda$26(C3.java:1173)
	at c3.C3.asUser(C3.java:1844)
	at c3.C3.asUser(C3.java:833)
	at c3.platform.async.MapReduceQueue_Methods.compute(MapReduceQueue_Methods.java:31)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.platform.async.InvalidationQueue_Methods.compute(InvalidationQueue_Methods.java:1085)
	at c3.platform.async.InvalidationQueue_Methods.doDispatchCompute(InvalidationQueue_Methods.java:301)
	at c3.platform.async.InvalidationQueue_Methods.dispatchCompute(InvalidationQueue_Methods.java:270)
	at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.C3.callWithSecondaryKey(C3.java:277)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$19(InvalidationQueue_Processor_Methods.java:418)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$16(InvalidationQueue_Processor_Methods.java:417)
	at c3.platform.async.Promise_Methods.lambda$1(Promise_Methods.java:32)
	at c3.platform.async.FulfillablePromise_Impl.lambda$12(FulfillablePromise_Impl.java:285)
	at c3.C3.callInLocalJvmApp(C3.java:178)
	at c3.platform.async.FulfillablePromise_Impl._run(FulfillablePromise_Impl.java:284)
	at c3.platform.async.Promise_Methods.lambda$0(Promise_Methods.java:32)
	at c3.C3.lambda$5(C3.java:141)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.C3.lambda$4(C3.java:141)
	at c3.Executor.lambda$4(Executor.java:156)
	at c3.C3.runWithAppId(C3.java:1029)
	at c3.C3.runInApp(C3.java:1020)
	at c3.C3.lambda$46(C3.java:1417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)


Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }

Called from Java action ObjBatchMapReduceJob#map
Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

	at c3.platform.action.py.TurboPyInterpreter.callMethod(TurboPyInterpreter.java:172)
	at c3.platform.action.py.TurboPy.lambda$5(TurboPy.java:508)
	at c3.platform.typesys.type.TypeMeta_Methods.lambda$5(TypeMeta_Methods.java:288)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.callMethodType(Ctx.java:367)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:288)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:304)
	at c3.platform.typesys.type.TypeMeta_Impl.call(TypeMeta_Impl.java:4467)
	at c3.C3.dispatch(C3.java:448)
	at c3.platform.action.js.TurboJsMethod.callJava(TurboJsMethod.java:64)
	at c3.platform.action.js.TurboJsFunction.lambda$0(TurboJsFunction.java:34)
	at c3.platform.action.js.TurboJs.callWrapErr(TurboJs.java:839)
	at c3.platform.action.js.TurboJsFunction.call(TurboJsFunction.java:32)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.lambda_js_21._c_anonymous_1(lambda.js:11)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at c3.platform.action.js.TurboJs.lambda$15(TurboJs.java:432)
	at c3.platform.action.js.TurboJs.withRhinoContext(TurboJs.java:779)
	at c3.platform.action.js.TurboJs.lambda$11(TurboJs.java:413)
	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:358)
	... 82 more

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }

	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:373)
	at c3.platform.action.js.TurboJs.execLambda(TurboJs.java:412)
	at c3.platform.typesys.value.Lambda_Methods.applyJs(Lambda_Methods.java:95)
	at c3.platform.typesys.value.Lambda_Impl.applyJs(Lambda_Impl.java:345)
	at c3.platform.typesys.value.Lambda_Methods.apply(Lambda_Methods.java:69)
	at c3.platform.typesys.value.Lambda_Methods.call(Lambda_Methods.java:106)
	at c3.platform.typesys.value.Lambda_Impl.call(Lambda_Impl.java:303)
	at c3.platform.typesys.value.Lambda_Methods$1.call(Lambda_Methods.java:467)
	at c3.platform.typesys.util.function.AnyFunction$1.accept(AnyFunction.java:40)
	at c3.platform.cloud.apache.mapr.ObjBatchMapReduceJob_Methods.map(ObjBatchMapReduceJob_Methods.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	... 68 more

Called from Java action ObjBatchMapReduceJob#map

	at c3.platform.typesys.type.MethodType_Methods.handleException(MethodType_Methods.java:214)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:227)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$112(MapReduce_SubtypeImpl.java:1959)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:384)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.map(MapReduce_SubtypeImpl.java:1959)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMapForSubBatch(MapReduce_Methods.java:736)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMap(MapReduce_Methods.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$129(MapReduce_SubtypeImpl.java:2050)
	at c3.Ctx.lambda$13(Ctx.java:416)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.run(Ctx.java:415)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.dispatchMap(MapReduce_SubtypeImpl.java:2050)
	at c3.platform.async.MapReduceQueue_Methods.lambda$0(MapReduceQueue_Methods.java:70)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.C3.lambda$26(C3.java:1173)
	at c3.C3.asUser(C3.java:1844)
	at c3.C3.asUser(C3.java:833)
	at c3.platform.async.MapReduceQueue_Methods.compute(MapReduceQueue_Methods.java:31)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.platform.async.InvalidationQueue_Methods.compute(InvalidationQueue_Methods.java:1085)
	at c3.platform.async.InvalidationQueue_Methods.doDispatchCompute(InvalidationQueue_Methods.java:301)
	at c3.platform.async.InvalidationQueue_Methods.dispatchCompute(InvalidationQueue_Methods.java:270)
	at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.C3.callWithSecondaryKey(C3.java:277)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$19(InvalidationQueue_Processor_Methods.java:418)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$16(InvalidationQueue_Processor_Methods.java:417)
	at c3.platform.async.Promise_Methods.lambda$1(Promise_Methods.java:32)
	at c3.platform.async.FulfillablePromise_Impl.lambda$12(FulfillablePromise_Impl.java:285)
	at c3.C3.callInLocalJvmApp(C3.java:178)
	at c3.platform.async.FulfillablePromise_Impl._run(FulfillablePromise_Impl.java:284)
	at c3.platform.async.Promise_Methods.lambda$0(Promise_Methods.java:32)
	at c3.C3.lambda$5(C3.java:141)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.C3.lambda$4(C3.java:141)
	at c3.Executor.lambda$4(Executor.java:156)
	at c3.C3.runWithAppId(C3.java:1029)
	at c3.C3.runInApp(C3.java:1020)
	at c3.C3.lambda$46(C3.java:1417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)


Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }
Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

	at c3.platform.action.py.TurboPyInterpreter.callMethod(TurboPyInterpreter.java:172)
	at c3.platform.action.py.TurboPy.lambda$5(TurboPy.java:508)
	at c3.platform.typesys.type.TypeMeta_Methods.lambda$5(TypeMeta_Methods.java:288)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.callMethodType(Ctx.java:367)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:288)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:304)
	at c3.platform.typesys.type.TypeMeta_Impl.call(TypeMeta_Impl.java:4467)
	at c3.C3.dispatch(C3.java:448)
	at c3.platform.action.js.TurboJsMethod.callJava(TurboJsMethod.java:64)
	at c3.platform.action.js.TurboJsFunction.lambda$0(TurboJsFunction.java:34)
	at c3.platform.action.js.TurboJs.callWrapErr(TurboJs.java:839)
	at c3.platform.action.js.TurboJsFunction.call(TurboJsFunction.java:32)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.lambda_js_21._c_anonymous_1(lambda.js:11)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at c3.platform.action.js.TurboJs.lambda$15(TurboJs.java:432)
	at c3.platform.action.js.TurboJs.withRhinoContext(TurboJs.java:779)
	at c3.platform.action.js.TurboJs.lambda$11(TurboJs.java:413)
	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:358)
	... 82 more

Called from JavaScript action Lambda.applyJs executing in runtime js on server (lambda.js)
    10  chunkerSpec = Genai.SourceFile.Chunker.UniversalChunker.Spec.make({'chunker': Genai.SourceFile.Chunker.Univer‚Ä¶
  > 11      chunkerSpec.chunker.chunkFilesBatch(objs, chunkerSpec);
    12  }

	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:373)
	at c3.platform.action.js.TurboJs.execLambda(TurboJs.java:412)
	at c3.platform.typesys.value.Lambda_Methods.applyJs(Lambda_Methods.java:95)
	at c3.platform.typesys.value.Lambda_Impl.applyJs(Lambda_Impl.java:345)
	at c3.platform.typesys.value.Lambda_Methods.apply(Lambda_Methods.java:69)
	at c3.platform.typesys.value.Lambda_Methods.call(Lambda_Methods.java:106)
	at c3.platform.typesys.value.Lambda_Impl.call(Lambda_Impl.java:303)
	at c3.platform.typesys.value.Lambda_Methods$1.call(Lambda_Methods.java:467)
	at c3.platform.typesys.util.function.AnyFunction$1.accept(AnyFunction.java:40)
	at c3.platform.cloud.apache.mapr.ObjBatchMapReduceJob_Methods.map(ObjBatchMapReduceJob_Methods.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$112(MapReduce_SubtypeImpl.java:1959)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:384)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.map(MapReduce_SubtypeImpl.java:1959)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMapForSubBatch(MapReduce_Methods.java:736)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMap(MapReduce_Methods.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$129(MapReduce_SubtypeImpl.java:2050)
	at c3.Ctx.lambda$13(Ctx.java:416)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.run(Ctx.java:415)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.dispatchMap(MapReduce_SubtypeImpl.java:2050)
	at c3.platform.async.MapReduceQueue_Methods.lambda$0(MapReduceQueue_Methods.java:70)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.C3.lambda$26(C3.java:1173)
	at c3.C3.asUser(C3.java:1844)
	at c3.C3.asUser(C3.java:833)
	at c3.platform.async.MapReduceQueue_Methods.compute(MapReduceQueue_Methods.java:31)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.platform.async.InvalidationQueue_Methods.compute(InvalidationQueue_Methods.java:1085)
	at c3.platform.async.InvalidationQueue_Methods.doDispatchCompute(InvalidationQueue_Methods.java:301)
	at c3.platform.async.InvalidationQueue_Methods.dispatchCompute(InvalidationQueue_Methods.java:270)
	at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.C3.callWithSecondaryKey(C3.java:277)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$19(InvalidationQueue_Processor_Methods.java:418)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$16(InvalidationQueue_Processor_Methods.java:417)
	at c3.platform.async.Promise_Methods.lambda$1(Promise_Methods.java:32)
	at c3.platform.async.FulfillablePromise_Impl.lambda$12(FulfillablePromise_Impl.java:285)
	at c3.C3.callInLocalJvmApp(C3.java:178)
	at c3.platform.async.FulfillablePromise_Impl._run(FulfillablePromise_Impl.java:284)
	at c3.platform.async.Promise_Methods.lambda$0(Promise_Methods.java:32)
	at c3.C3.lambda$5(C3.java:141)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.C3.lambda$4(C3.java:141)
	at c3.Executor.lambda$4(Executor.java:156)
	at c3.C3.runWithAppId(C3.java:1029)
	at c3.C3.runInApp(C3.java:1020)
	at c3.C3.lambda$46(C3.java:1417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)


Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch
Error invoking Python method Genai.SourceFile.Chunker.Universal#chunkFilesBatch executing in runtime py-chunker on server using py4j: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out')) (Genai.SourceFile.Chunker.py#262)
    File "/c3/genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py", line 141, in chunkFilesBatch
      chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)

    File "/c3/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/c3/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

  Traceback (most recent call last):

  
  During handling of the above exception, another exception occurred:
  

  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fadff4e9460>: Failed to establish a new connection: [Errno 110] Connection timed out'))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
      retries = retries.increment(

    File "/usr/local/share/c3/runtimes/7142613454230771420/py-chunker-server-py4j/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
      resp = conn.urlopen(

  Traceback (most recent call last):

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    260          if textSplitterSpec.splitterModule["name"] == "langchain":
    261              text_splitter_module = importlib.import_module(textSplitterSpec.splitterModule["importPath"])
  > 262              splitters += [getattr(text_splitter_module, textSplitterSpec.textSplitter)(**vars)]
    263          elif textSplitterSpec.splitterModule["name"] == "custom":
    264              # custom chunker should inherit from langchain.text_splitter.TextSplitter

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.PyPdf.py
    18      from langchain.document_loaders.pdf import PyPDFLoader
    19  
  > 20      splitter = cls.splitterHelper(chunkerSpec, [])
    21  
    22      def loader_lambda(x):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    78          # use list here because source_files and local_paths are now tuples from zip(* ... )
  > 79          result = chunker_type.doChunkFilesBatch(list(source_files), list(local_paths), ext_to_chunker[ext])
    80          passages_map.putAll(result.passagesMap)
    81          successful_files.extend(result.objList.objs)

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 583, in addToStackFrame

    File "/platform/src/remote/ServerConnection.py", line 2002, in funcForStayInRuntime

    /genAiBase/src/sources/chunkers/Genai.SourceFile.Chunker.py
    140      try:
  > 141          chunk_files_result = cls.doChunkFilesBatch(files, local_paths, chunkerSpec)
    142      finally:
    143          if os.path.exists(local_dir):

    File "/platform/src/remote/ServerConnection.py", line 2019, in inlineMethodWithErrorHandling

    File "/platform/src/remote/ServerConnection.py-server.py", line 891, in wrap_and_call

    File "/platform/src/remote/ServerConnection.py-server.py", line 895, in wrapCallAndCatch

	at c3.platform.action.py.TurboPyInterpreter.callMethod(TurboPyInterpreter.java:172)
	at c3.platform.action.py.TurboPy.lambda$5(TurboPy.java:508)
	at c3.platform.typesys.type.TypeMeta_Methods.lambda$5(TypeMeta_Methods.java:288)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.callMethodType(Ctx.java:367)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:288)
	at c3.platform.typesys.type.TypeMeta_Methods.call(TypeMeta_Methods.java:304)
	at c3.platform.typesys.type.TypeMeta_Impl.call(TypeMeta_Impl.java:4467)
	at c3.C3.dispatch(C3.java:448)
	at c3.platform.action.js.TurboJsMethod.callJava(TurboJsMethod.java:64)
	at c3.platform.action.js.TurboJsFunction.lambda$0(TurboJsFunction.java:34)
	at c3.platform.action.js.TurboJs.callWrapErr(TurboJs.java:839)
	at c3.platform.action.js.TurboJsFunction.call(TurboJsFunction.java:32)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:55)
	at org.mozilla.javascript.gen.lambda_js_21._c_anonymous_1(lambda.js:11)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.gen.lambda_js_21.call(lambda.js)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at c3.platform.action.js.TurboJs.lambda$15(TurboJs.java:432)
	at c3.platform.action.js.TurboJs.withRhinoContext(TurboJs.java:779)
	at c3.platform.action.js.TurboJs.lambda$11(TurboJs.java:413)
	at c3.platform.action.js.TurboJs.handleC3Error(TurboJs.java:358)
	at c3.platform.action.js.TurboJs.execLambda(TurboJs.java:412)
	at c3.platform.typesys.value.Lambda_Methods.applyJs(Lambda_Methods.java:95)
	at c3.platform.typesys.value.Lambda_Impl.applyJs(Lambda_Impl.java:345)
	at c3.platform.typesys.value.Lambda_Methods.apply(Lambda_Methods.java:69)
	at c3.platform.typesys.value.Lambda_Methods.call(Lambda_Methods.java:106)
	at c3.platform.typesys.value.Lambda_Impl.call(Lambda_Impl.java:303)
	at c3.platform.typesys.value.Lambda_Methods$1.call(Lambda_Methods.java:467)
	at c3.platform.typesys.util.function.AnyFunction$1.accept(AnyFunction.java:40)
	at c3.platform.cloud.apache.mapr.ObjBatchMapReduceJob_Methods.map(ObjBatchMapReduceJob_Methods.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$112(MapReduce_SubtypeImpl.java:1959)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:384)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.map(MapReduce_SubtypeImpl.java:1959)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMapForSubBatch(MapReduce_Methods.java:736)
	at c3.platform.cloud.apache.mapr.MapReduce_Methods.dispatchMap(MapReduce_Methods.java:551)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.platform.typesys.type.TypeMeta_Methods.callFromCodeGen(TypeMeta_Methods.java:359)
	at c3.platform.typesys.type.TypeMeta_Impl.callFromCodeGen(TypeMeta_Impl.java:4491)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.lambda$129(MapReduce_SubtypeImpl.java:2050)
	at c3.Ctx.lambda$13(Ctx.java:416)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.run(Ctx.java:415)
	at c3.platform.cloud.apache.mapr.MapReduce_SubtypeImpl.dispatchMap(MapReduce_SubtypeImpl.java:2050)
	at c3.platform.async.MapReduceQueue_Methods.lambda$0(MapReduceQueue_Methods.java:70)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.C3.lambda$26(C3.java:1173)
	at c3.C3.asUser(C3.java:1844)
	at c3.C3.asUser(C3.java:833)
	at c3.platform.async.MapReduceQueue_Methods.compute(MapReduceQueue_Methods.java:31)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.platform.async.InvalidationQueue_Methods.compute(InvalidationQueue_Methods.java:1085)
	at c3.platform.async.InvalidationQueue_Methods.doDispatchCompute(InvalidationQueue_Methods.java:301)
	at c3.platform.async.InvalidationQueue_Methods.dispatchCompute(InvalidationQueue_Methods.java:270)
	at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at c3.platform.typesys.type.MethodType_Methods.lambda$7(MethodType_Methods.java:225)
	at c3.C3.lambda$14(C3.java:601)
	at c3.ClusterCtx.lambda$12(ClusterCtx.java:385)
	at c3.Ctx.call(Ctx.java:396)
	at c3.C3.dispatch(C3.java:599)
	at c3.C3.callWithSecondaryKey(C3.java:277)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$19(InvalidationQueue_Processor_Methods.java:418)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.platform.async.InvalidationQueue_Processor_Methods.lambda$16(InvalidationQueue_Processor_Methods.java:417)
	at c3.platform.async.Promise_Methods.lambda$1(Promise_Methods.java:32)
	at c3.platform.async.FulfillablePromise_Impl.lambda$12(FulfillablePromise_Impl.java:285)
	at c3.C3.callInLocalJvmApp(C3.java:178)
	at c3.platform.async.FulfillablePromise_Impl._run(FulfillablePromise_Impl.java:284)
	at c3.platform.async.Promise_Methods.lambda$0(Promise_Methods.java:32)
	at c3.C3.lambda$5(C3.java:141)
	at c3.C3.lambda$50(C3.java:1445)
	at c3.Ctx.asRoot(Ctx.java:736)
	at c3.C3.lambda$4(C3.java:141)
	at c3.Executor.lambda$4(Executor.java:156)
	at c3.C3.runWithAppId(C3.java:1029)
	at c3.C3.runInApp(C3.java:1020)
	at c3.C3.lambda$46(C3.java:1417)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

## üîó Links

## **üè∑Ô∏èTags**

- #02-2024
